version: '3.8'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: demander
      MYSQL_USER: demander
      MYSQL_PASSWORD: developerdoug123
      MYSQL_ROOT_PASSWORD: developerdoug123
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  dbdata:
